String repositoryUrl = 'https://github.com/tonimitrevski/calculator'

def checkoutBranch(String repoUrl, String branch) {
	checkout scm: [
			$class: 'GitSCM',
			branches: [[name: branch]],
			doGenerateSubmoduleConfigurations: false,
			submoduleCfg: [],
			userRemoteConfigs: [[url: repoUrl]]
	]
}

def checkoutBranchUtils
def checkoutBranchResult

pipeline {
	agent any
	parameters {
		string(name: 'Branch', description: 'Chose branch version')
		choice(name: 'Release', choices: ['New', 'Bugfix'], description: 'Pick something')
	}
	stages {
		stage('Checkout') {
			steps {
        checkout scm
        checkoutBranch(repositoryUrl, 'master')
        script {
          sh 'ls -a'
          sh 'pwd'
          echo params.Release
          checkoutBranchUtils = load "jenkins/release/src/checkoutBranch.groovy"
          checkoutBranchResult = checkoutBranchUtils.handle(params.Release)
        }

				echo checkoutBranchResult
			}
		}
	}
}
