String repositoryUrl = 'https://github.com/tonimitrevski/calculator'

def checkoutBranch(String repoUrl, String branch) {
	checkout scm: [
			$class: 'GitSCM',
			branches: [[name: branch]],
			doGenerateSubmoduleConfigurations: false,
			submoduleCfg: [],
			userRemoteConfigs: [[url: repoUrl]]
	]
}

def checkoutBranchUtils
def checkoutBranch

pipeline {
	agent any
	parameters {
		string(name: 'Branch', description: 'Chose branch version')
		choice(name: 'Release', choices: ['New', 'Bugfix'], description: 'Pick something')
	}
	stages {
		stage('Checkout') {
			steps {
        checkout scm
        checkoutBranch(repositoryUrl, 'master')

        checkoutBranchUtils = load "jenkins/release/src/checkoutBranch.groovy"
        checkoutBranch = checkoutBranchUtils.handle(params.Release)

				echo checkoutBranch
			}
		}
	}
}
